## Setup

```{r}
#| label: setup
library(tidyverse)
library(janitor)
library(data.table)
library(readxl)
```

## Autocoup Dataset

```{r}
#| label: autocoup
# read_data
Autocoup <- read_excel("Autocoup.xlsx")
# str(Autocoup)
# write_data
autocoup <- Autocoup |> 
  mutate(entry_date = as.Date(entry_date)) |> 
  write_csv("autocoup.csv")
# str(autocoup)
```

## PLAD Dataset

```{r}
download.file("https://dataverse.harvard.edu/api/access/datafile/10119324", "PLAD.xls")

# read_data
PLAD <- read_excel("PLAD.xls")
write_csv(PLAD, "PLAD.csv")
```

## Archigos Dataset

```{r}
#| label: archigos

# read_data
Archigos <- fread("http://ksgleditsch.com/data/1March_Archigos_4.1.txt", encoding = "Latin-1") 

# write_data
archigos <- Archigos |> 
  #update Léon M'ba of Babon
  mutate(
    startdate = ymd(startdate),
    enddate = ymd(enddate)
  ) |>
  filter(!obsid %in% c("GAB-1960", "GAB-1964-1")) |>
  mutate(
    startdate = case_when(
      obsid == "GAB-1964-2" ~ ymd("1960-08-17"),
      TRUE ~ startdate),
    entry = case_when(
      obsid == "GAB-1964-2" ~ "Regular",
      TRUE ~ entry)
  )
write_csv(archigos, "archigos.csv")
```

## Country Codes Dataset

```{r}
#| label: country_codes

# countrycode::codelist |> 
#   view()
```

## Upload Datasets

```{bash}
#| label: upload

git add .
git commit -m "Version $(date +%Y-%m-%d)"
git push
```
