## Setup

```{r}
#| label: setup
library(tidyverse)
library(janitor)
library(data.table)
library(readxl)
```

## Autocoup Dataset

```{r}
#| label: autocoup
# read_data
Autocoup <- read_excel("Autocoup.xlsx")
# str(Autocoup)
# write_data
autocoup <- Autocoup |> 
  mutate(entry_date = as.Date(entry_date)) 

write_csv(autocoup, "autocoup.csv")
# str(autocoup)
```

## PLAD Dataset

```{r}
download.file("https://dataverse.harvard.edu/api/access/datafile/10119324", "PLAD.xls")

# read_data
PLAD <- read_excel("PLAD.xls") |> 
  mutate(exit = case_when(
    exit == "Still in office" ~ "Still in Office",
    TRUE ~ exit
  ))
write_csv(PLAD, "PLAD.csv")

plad <- PLAD |> 
  select(country, continent, 1:6, entry, exit, gender, yrborn) |>
  mutate(
    startdate = dmy(startdate),
    enddate = dmy(enddate)
  ) |>
  filter(enddate - startdate > 270)
write_csv(plad, "plad.csv")
```

## Archigos Dataset

```{r}
#| label: archigos

# read_data
Archigos <- fread("http://ksgleditsch.com/data/1March_Archigos_4.1.txt", encoding = "Latin-1")

write_csv(Archigos, "Archigos.csv")

archigos <- Archigos |>
  mutate(startdate = ymd(startdate),
         enddate = ymd(enddate)) |> 
  #update Léon M'ba of Babon and Pution
  filter(!obsid %in% c("GAB-1960", "GAB-1964-1")) |>
  mutate(
    startdate = case_when(
      obsid == "GAB-1964-2" ~ ymd("1960-08-17"),
      obsid == "CHA-1990" ~ ymd("1990-12-2"),
      obsid == "RUS-2000" ~ ymd("1999-12-31"),
      TRUE ~ startdate),
    entry = case_when(
      obsid == "GAB-1964-2" ~ "Regular",
      TRUE ~ entry)
  )

write_csv(archigos, "archigos.csv")
```

## Leaders Dataset: Archigos and PLAD

```{r}
#| label: leaders_Reddy

leaders <- archigos |>
  filter(enddate - startdate > 270) |>
  full_join(plad, join_by(idacr, startdate), suffix = c(".archigos", ".plad")) |>
  group_by(idacr) |>
  fill(ccode, country, continent, .direction = "downup") |>
  ungroup() |>
  mutate(
    obsid = coalesce(obsid, plad_id),
    leader.archigos = coalesce(leader.archigos, leader.plad),
    enddate.archigos = coalesce(enddate.plad, enddate.archigos),
    entry.archigos = coalesce(entry.plad, entry.archigos),
    exit.archigos = coalesce(exit.plad, exit.archigos),
    enddate.archigos = if_else(exit.archigos == "Still in Office", Sys.Date(), enddate.archigos),
    gender.archigos = coalesce(gender.archigos, gender.plad),
    yrborn.archigos = coalesce(yrborn.archigos, as.numeric(yrborn.plad)),
    exitcode = coalesce(exitcode, exit.archigos)
  ) |> 
  select(1:4, country, continent, leader = leader.archigos, startdate, enddate = enddate.archigos, entry = entry.archigos, exit = exit.archigos, exitcode, gender = gender.archigos, yrborn = yrborn.archigos) |>
  arrange(ccode, startdate)
write.csv(leaders, "leaders.csv")
```

## Country Codes Dataset

```{r}
#| label: country_codes

# countrycode::codelist |>
#   view()
```

## REIGN Dataset

```{r}
#| label: reign

# regime <- democracyData::REIGN |> 
#   view()
```

## Political Violence Dataset: MEPV

```{r}
#| label: violence

download.file("http://www.systemicpeace.org/inscr/MEPVv2018.xls", "political_violence_2018.xls")

political_violence <- read_excel("political_violence_2018.xls")
write_csv(political_violence, "political_violence.csv")
```

## Upload Datasets

```{bash}
#| label: upload

git add .
git commit -m "Version $(date +%Y-%m-%d)"
git push
```
